export const INSERT_TEACHER_SUCCESS = "INSERT_TEACHER_SUCCESS";
export const INSERT_TEACHER_FAILURE = "INSERT_TEACHER_FAILURE";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAILURE = "UPDATE_TEACHER_FAILURE";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILURE = "DELETE_TEACHER_FAILURE";

export const INSERT_STUDENT_SUCCESS = "INSERT_STUDENT_SUCCESS";
export const INSERT_STUDENT_FAILURE = "INSERT_STUDENT_FAILURE";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE";

export const INSERT_CLASS_SUCCESS = "INSERT_CLASS_SUCCESS";
export const INSERT_CLASS_FAILURE = "INSERT_CLASS_FAILURE";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAILURE = "UPDATE_CLASS_FAILURE";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILURE = "DELETE_CLASS_FAILURE";

export const INSERT_SUBJECT_SUCCESS = "INSERT_SUBJECT_SUCCESS";
export const INSERT_SUBJECT_FAILURE = "INSERT_SUBJECT_FAILURE";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_FAILURE = "UPDATE_SUBJECT_FAILURE";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAILURE = "DELETE_SUBJECT_FAILURE";
